sonar.projectKey=abdellah0x0_agentic-devsecops-pipeline
sonar.organization=abdellah0x0abdellah0x0nfn3f93mf-abdellah0x0abdellah0x0abdellah0x07243782348

# Metadata
sonar.projectName=agentic-devsecops-pipeline
sonar.projectVersion=1.0

# Source folder 
sonar.sources=app

# Exclusions
sonar.exclusions=**/node_modules/**,**/public/**

sonar.sourceEncoding=UTF-8